{"uuid":"87f765a2-6da5-49fb-87e0-aab9ac9f3767","historyId":"b2a4935e891140876acafb2cf5f002f9","fullName":"localhost.bookstore.qa.testcases.LoginPageTest.loginTest","labels":[{"name":"package","value":"localhost.bookstore.qa.testcases.LoginPageTest"},{"name":"testClass","value":"localhost.bookstore.qa.testcases.LoginPageTest"},{"name":"testMethod","value":"loginTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Bookstore_LocalHost_React"},{"name":"subSuite","value":"localhost.bookstore.qa.testcases.LoginPageTest"},{"name":"host","value":"DESKTOP-23R1U7L"},{"name":"thread","value":"5868@DESKTOP-23R1U7L.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Authentication"},{"name":"severity","value":"blocker"}],"links":[],"name":"loginTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [http://localhost:3000/dashboard] but found [http://localhost:3000/]","trace":"java.lang.AssertionError: expected [http://localhost:3000/dashboard] but found [http://localhost:3000/]\r\n\tat org.testng.Assert.fail(Assert.java:110)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1577)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:149)\r\n\tat org.testng.Assert.assertEquals(Assert.java:131)\r\n\tat org.testng.Assert.assertEquals(Assert.java:655)\r\n\tat org.testng.Assert.assertEquals(Assert.java:665)\r\n\tat localhost.bookstore.qa.testcases.LoginPageTest.loginTest(LoginPageTest.java:57)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\r\n\tat org.testng.TestRunner.run(TestRunner.java:602)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\r\n\tat org.testng.TestNG.run(TestNG.java:1067)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify login with valid credentials","steps":[],"attachments":[],"parameters":[{"name":"arg2","value":"true"},{"name":"arg1","value":"Pass@123"},{"name":"arg0","value":"saragadam.neeraja@bridgelabz.com"}],"start":1711686447803,"stop":1711686455991}